# -*- coding: utf-8 -*-
"""Netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vUhjTSOKI2ZSIuxrNNxIYjMUijMF2M7
"""



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

netflix_dataset = pd.read_csv('/content/netflix.csv')

netflix_dataset.head(5)

netflix_dataset.describe()

netflix_dataset.isnull().sum()

#Distribution of IMDb scores
plt.figure(figsize=(10, 6))
sns.histplot(netflix_dataset['imdb_score'], kde=True, color='skyblue')
plt.title('IMDb Scores')
plt.xlabel('IMDb Score')
plt.ylabel('Frequency')
plt.show()

# Relationship between IMDb score and runtime
plt.figure(figsize=(10, 6))
sns.scatterplot(data=netflix_dataset, x='runtime', y='imdb_score', color='coral')
plt.title('IMDb Score vs Runtime')
plt.xlabel('Runtime (minutes)')
plt.ylabel('IMDb Score')
plt.show()

# Top 10 languages
top_languages = netflix_dataset['language'].value_counts().head(10)
plt.figure(figsize=(10, 6))
top_languages.plot(kind='bar', color='lightgreen')
plt.title('Top 10 Languages')
plt.xlabel('Language')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

# Release year distribution
plt.figure(figsize=(12, 8))
sns.histplot(netflix_dataset['year'], bins=20, kde=True, color='salmon')
plt.title('Release Year Distribution')
plt.xlabel('Year')
plt.ylabel('Frequency')
plt.show()

# Relationship between IMDb score & premiere year
plt.figure(figsize=(10, 6))
sns.boxplot(data=netflix_dataset, x='year', y='imdb_score', palette='Set2')
plt.title('IMDb Score Distribution by Premiere Year')
plt.xlabel('Premiere Year')
plt.ylabel('IMDb Score')
plt.xticks(rotation=90)
plt.show()

# Runtime distribution
plt.figure(figsize=(10, 6))
sns.histplot(netflix_dataset['runtime'], bins=20, kde=True, color='skyblue')
plt.title('Runtime Distribution')
plt.xlabel('Runtime (minutes)')
plt.ylabel('Frequency')
plt.show()

# IMDb score distribution over time
plt.figure(figsize=(12, 8))
sns.lineplot(data=netflix_dataset, x='year', y='imdb_score', color='orange')
plt.title('IMDb Score Trend Over Time')
plt.xlabel('Year')
plt.ylabel('IMDb Score')
plt.xticks(rotation=90)
plt.show()

# Count of titles by premiere year
plt.figure(figsize=(12, 8))
sns.countplot(data=netflix_dataset, x='year', palette='rocket')
plt.title('Count of Titles by Premiere Year')
plt.xlabel('Premiere Year')
plt.ylabel('Count')
plt.xticks(rotation=90)
plt.show()

# Relationship between IMDb score & language for top 5 languages
top_5_languages = netflix_dataset['language'].value_counts().head(5).index
top_5_data = netflix_dataset[netflix_dataset['language'].isin(top_5_languages)]
plt.figure(figsize=(12, 8))
sns.boxplot(data=top_5_data, x='language', y='imdb_score', palette='muted')
plt.title('IMDb Score Distribution by Top 5 Languages')
plt.xlabel('Language')
plt.ylabel('IMDb Score')
plt.xticks(rotation=45)
plt.show()